export const profile = {

    title: "User Profile",
    info: "Information",
    update: "Update Profile",
    login: "Login",
    placeholderLogin: "Enter your login",
    email: "Email",
    placeholderEmail: "Enter your email",
    patternEmail: "Invalid email address",

    twoFA:{
        topic: "Two-factor authentication",
        first: "1. Completing this process requires an authenticator app, such as Google Authenticator",
        second: "2. Scan the QR code with your authenticator",
        secondText: "If you're unable to scan the code, you can manually enter this secret key into your authenticator app.",
        third: "3. Once you've scanned the QR code above, input the six-digit code generated by your authenticator.",
        verify: "Verify",
        loading: "Loading QR...",
        toast:{
          successConnection:"Successful Two Factor Authentication connection",
          successCopy:"Copied to clipboard",
          errorConnection:"Fail Two Factor Authentication connection",
        }
    },
    twoFADisable:{
        topic: "Two-factor authentication",
        passwordTopic: "Password",
        first: "1. To disable 2FA, enter your password and the six-digit code from the Google Authenticator app below, then click “Disable”.",
        placeholderPassword: "Enter your password",
        FATopic: "2FA Code",
        placeholderFA: "Enter your 2FA Code",
        required: "This is required.",
        disable: "Disable",
        toast:{
          successDisabling:"Successful disabling Two Factor Authentication",
        }
    },
    changePassword:{
        topic: "Change Password",
        oldPasswordTopic: "Old Password",
        placeholderOldPassword: "Enter your old password",
        FATopic: "2FA Code",
        placeholderFA: "Enter your 2FA Code",
        newPasswordTopic: "New Password",
        placeholderNewPassword: "Enter your new password",
        patternNewPassword: "Min lenght is 6.",
        confirmNewPassword: "Confirm new password",
        patternConfirmPassword: "Passwords do not match.",
        placeholderConfirmPassword: "Repeat your new password",
        required: "This is required.",
        save: "Save",
    },

    premium: {
      title: "Upgrade to Premium",
      subtitle: "Unlock advanced features and take your crypto experience to the next level",
      features: {
        analyticsTitle: "Advanced Analytics",
        analyticsDescription: "Get detailed insights and performance metrics",
        notificationsTitle: "Push Notifications",
        notificationsDescription: "Real-time alerts for price changes and updates",
        walletsTitle: "Unlimited Wallets",
        walletsDescription: "Connect unlimited wallets and portfolios"
      },
      guarantee: "Cancel anytime • 30-day money-back guarantee",
      activateButton: "Activate Premium",
      activating: "Activating Premium..."
    }

};